// Carousel data in two languages
const carouselData = {
  es: [
    {
      src: "img/hotel-selector.webp",
      alt: "Hotel Selector",
      title: "Mainpage (Selector de hotel)",
      desc: "Pantalla principal donde el usuario puede seleccionar el hotel para acceder a su respectivo login, dependiendo de en que hotel se aloje."
    },
    {
      src: "img/mainpage.webp",
      alt: "Mainpage (Info y Contacto)",
      title: "Mainpage (Info y Contacto)",
      desc: "Vista de información y contacto de Jhoola."
    },
    {
      src: "img/login.webp",
      alt: "Login",
      title: "Login",
      desc: "Pantalla de inicio de sesión para usuarios registrados."
    },
    {
      src: "img/jhoola-profile.webp",
      alt: "Perfil de reservas",
      title: "Reservas del usuario",
      desc: "Área personal de cada cliente, donde puede ver sus reservas y gestionarlas."
    },
    {
      src: "img/form.webp",
      alt: "Formulario",
      title: "Formulario de reserva",
      desc: "Formulario para que los usuarios realicen nuevas reservas, teniendo en cuenta el dia de la semana y el horario escogido (Mañana, tarde o todo el día)."
    },
    {
      src: "img/map.webp",
      alt: "Mapa de reserva",
      title: "Mapa de reserva",
      desc: "Visualización de la distribución de las hamacas disponibles y reservadas en el hotel, para que los usuarios puedan escoger las que deseen reservar, con control de concurrencia."
    },
    {
      src: "img/stripe.webp",
      alt: "Stripe",
      title: "Pago con Stripe",
      desc: "Pantalla de pago seguro mediante Stripe."
    },
    {
      src: "img/pdf.webp",
      alt: "PDF",
      title: "PDF de confirmación de reserva",
      desc: "Documento PDF generado tras la reserva y el pago de las hamacas, con un código QR que puede ser leído por usuarios administradores para la confirmación de la reserva a la hora de acceder a la hamaca."
    },
    {
      src: "img/admin-stats.webp",
      alt: "Admin Stats",
      title: "Panel de administración (Estadísticas)",
      desc: "Vista de estadísticas para administradores del hotel en cuanto al número de reservas, número de clientes, hamacas (o diferentes productos dependiendo del hotel) y dinero generado gracias a la aplicación."
    },
    {
      src: "img/admin.webp",
      alt: "Admin",
      title: "Panel de administración (Usuarios)",
      desc: "Panel para la gestión de los diferentes activos del hotel en la aplicación, en este caso, los usuarios. Se puede realizar un CRUD en todas las categorías"
    }
  ],
  en: [
    {
      src: "img/hotel-selector.webp",
      alt: "Hotel Selector",
      title: "Mainpage (Hotel Selector)",
      desc: "Main screen where the user can select the hotel to access its corresponding login, depending on where they are staying."
    },
    {
      src: "img/mainpage.webp",
      alt: "Mainpage (Info and Contact)",
      title: "Mainpage (Info and Contact)",
      desc: "Information and contact view of Jhoola."
    },
    {
      src: "img/login.webp",
      alt: "Login",
      title: "Login",
      desc: "Login screen for registered users."
    },
    {
      src: "img/jhoola-profile.webp",
      alt: "Booking Profile",
      title: "User Bookings",
      desc: "Personal area for each client where they can view and manage their bookings."
    },
    {
      src: "img/form.webp",
      alt: "Booking Form",
      title: "Booking Form",
      desc: "Form for users to make new bookings, taking into account the day of the week and selected time slot (morning, afternoon, or full day)."
    },
    {
      src: "img/map.webp",
      alt: "Booking Map",
      title: "Booking Map",
      desc: "Visual representation of the available and booked sunbeds in the hotel, allowing users to select which ones they want to reserve, with concurrency control."
    },
    {
      src: "img/stripe.webp",
      alt: "Stripe",
      title: "Stripe Payment",
      desc: "Secure payment screen using Stripe."
    },
    {
      src: "img/pdf.webp",
      alt: "PDF",
      title: "Booking Confirmation PDF",
      desc: "PDF document generated after booking and payment of the sunbeds, including a QR code that can be scanned by administrators to confirm the booking upon access."
    },
    {
      src: "img/admin-stats.webp",
      alt: "Admin Stats",
      title: "Admin Panel (Statistics)",
      desc: "Statistics view for hotel administrators showing the number of bookings, clients, sunbeds (or different products depending on the hotel), and revenue generated by the app."
    },
    {
      src: "img/admin.webp",
      alt: "Admin",
      title: "Admin Panel (Users)",
      desc: "Panel for managing the hotel's various assets in the application — in this case, users. Full CRUD operations available for all categories."
    }
  ]
};

const currentLang = document.documentElement.lang === 'en' ? 'en' : 'es';
let currentSlide = 0;

function renderCarousel() {
  const data = carouselData[currentLang];
  const img = document.getElementById('carousel-img');
  const title = document.getElementById('carousel-title');
  const desc = document.getElementById('carousel-desc');
  img.src = data[currentSlide].src;
  img.alt = data[currentSlide].alt;
  title.textContent = data[currentSlide].title;
  desc.textContent = data[currentSlide].desc;
}

function nextSlide() {
  const data = carouselData[currentLang];
  currentSlide = (currentSlide + 1) % data.length;
  renderCarousel();
}

function prevSlide() {
  const data = carouselData[currentLang];
  currentSlide = (currentSlide - 1 + data.length) % data.length;
  renderCarousel();
}

document.addEventListener('DOMContentLoaded', function () {
  const prevBtn = document.getElementById('carousel-prev');
  const nextBtn = document.getElementById('carousel-next');
  prevBtn.addEventListener('click', prevSlide);
  nextBtn.addEventListener('click', nextSlide);
  renderCarousel();
});
