// Carousel data for Jhoola project
const carouselData = {
  jhoola: {
    es: [
      {
        src: "img/jhoola/hotel-selector.webp",
        alt: "Página principal (Selector de hotel)",
        title: "Página principal (Selector de hotel)",
        desc: "Pantalla principal donde el usuario puede seleccionar el hotel para acceder a su respectivo login, dependiendo de en que hotel se aloje."
      },
      {
        src: "img/jhoola/mainpage.webp",
        alt: "Mainpage (Info y Contacto)",
        title: "Mainpage (Info y Contacto)",
        desc: "Vista de información y contacto de Jhoola."
      },
      {
        src: "img/jhoola/login.webp",
        alt: "Login",
        title: "Login",
        desc: "Pantalla de inicio de sesión para usuarios registrados."
      },
      {
        src: "img/jhoola/jhoola-profile.webp",
        alt: "Perfil de reservas",
        title: "Reservas del usuario",
        desc: "Área personal de cada cliente, donde puede ver sus reservas y gestionarlas."
      },
      {
        src: "img/jhoola/form.webp",
        alt: "Formulario",
        title: "Formulario de reserva",
        desc: "Formulario para que los usuarios realicen nuevas reservas, teniendo en cuenta el dia de la semana y el horario escogido (Mañana, tarde o todo el día)."
      },
      {
        src: "img/jhoola/map.webp",
        alt: "Mapa de reserva",
        title: "Mapa de reserva",
        desc: "Visualización de la distribución de las hamacas disponibles y reservadas en el hotel, para que los usuarios puedan escoger las que deseen reservar, con control de concurrencia."
      },
      {
        src: "img/jhoola/stripe.webp",
        alt: "Stripe",
        title: "Pago con Stripe",
        desc: "Pantalla de pago seguro mediante Stripe."
      },
      {
        src: "img/jhoola/pdf.webp",
        alt: "PDF",
        title: "PDF de confirmación de reserva",
        desc: "Documento PDF generado tras la reserva y el pago de las hamacas, con un código QR que puede ser leído por usuarios administradores para la confirmación de la reserva a la hora de acceder a la hamaca."
      },
      {
        src: "img/jhoola/admin-stats.webp",
        alt: "Admin Stats",
        title: "Panel de administración (Estadísticas)",
        desc: "Vista de estadísticas para administradores del hotel en cuanto al número de reservas, número de clientes, hamacas (o diferentes productos dependiendo del hotel) y dinero generado gracias a la aplicación."
      },
      {
        src: "img/jhoola/admin.webp",
        alt: "Admin",
        title: "Panel de administración (Usuarios)",
        desc: "Panel para la gestión de los diferentes activos del hotel en la aplicación, en este caso, los usuarios. Se puede realizar un CRUD en todas las categorías"
      }
    ],
    en: [
      {
        src: "img/jhoola/hotel-selector.webp",
        alt: "Mainpage (Hotel Selector)",
        title: "Mainpage (Hotel Selector)",
        desc: "Main screen where the user can select the hotel to access its corresponding login, depending on where they are staying."
      },
      {
        src: "img/jhoola/mainpage.webp",
        alt: "Mainpage (Info and Contact)",
        title: "Mainpage (Info and Contact)",
        desc: "Information and contact view of Jhoola."
      },
      {
        src: "img/jhoola/login.webp",
        alt: "Login",
        title: "Login",
        desc: "Login screen for registered users."
      },
      {
        src: "img/jhoola/jhoola-profile.webp",
        alt: "Booking Profile",
        title: "User Bookings",
        desc: "Personal area for each client where they can view and manage their bookings."
      },
      {
        src: "img/jhoola/form.webp",
        alt: "Booking Form",
        title: "Booking Form",
        desc: "Form for users to make new bookings, taking into account the day of the week and selected time slot (morning, afternoon, or full day)."
      },
      {
        src: "img/jhoola/map.webp",
        alt: "Booking Map",
        title: "Booking Map",
        desc: "Visual representation of the available and booked sunbeds in the hotel, allowing users to select which ones they want to reserve, with concurrency control."
      },
      {
        src: "img/jhoola/stripe.webp",
        alt: "Stripe",
        title: "Stripe Payment",
        desc: "Secure payment screen using Stripe."
      },
      {
        src: "img/jhoola/pdf.webp",
        alt: "PDF",
        title: "Booking Confirmation PDF",
        desc: "PDF document generated after booking and payment of the sunbeds, including a QR code that can be scanned by administrators to confirm the booking upon access."
      },
      {
        src: "img/jhoola/admin-stats.webp",
        alt: "Admin Stats",
        title: "Admin Panel (Statistics)",
        desc: "Statistics view for hotel administrators showing the number of bookings, clients, sunbeds (or different products depending on the hotel), and revenue generated by the app."
      },
      {
        src: "img/jhoola/admin.webp",
        alt: "Admin",
        title: "Admin Panel (Users)",
        desc: "Panel for managing the hotel's various assets in the application — in this case, users. Full CRUD operations available for all categories."
      }
    ]
  },

  ot23: {
    es: [
      {
        src: "img/ot23/main.webp",
        alt: "Página principal",
        title: "Página principal",
        desc: "Pantalla principal con acceso a la información de los profesores, alumnos y jurado del programa Operación Triunfo 2023."
      },
      {
        src: "img/ot23/list.webp",
        alt: "Listado",
        title: "Listado de elementos",
        desc: "Pantalla donde se muestra una lista de elementos disponibles para el usuario dependiendo de la sección escogida, en este caso, los alumnos."
      },
      {
        src: "img/ot23/detail.webp",
        alt: "Detalle",
        title: "Detalle del elemento",
        desc: "Vista detallada de un elemento específico seleccionado desde la lista, en este caso el alumno Álex Márquez."
      },
      {
        src: "img/ot23/search_result.webp",
        alt: "Resultado de búsqueda",
        title: "Resultado de búsqueda",
        desc: "Pantalla con los resultados filtrados según los criterios introducidos por el usuario. El filtro tiene en cuenta los nombres y apellidos en el caso de los jueces, a los cuales les sumamos las ciudades y estilos de música para los alumnos, y las materias impartidas en el caso de los profesores."
      }
    ],
    en: [
      {
        src: "img/ot23/main.webp",
        alt: "Main page",
        title: "Main page",
        desc: "Main screen with access to the information of the teachers, students and jury of the program Operación Triunfo 2023."
              },
        {
        src: "img/ot23/list.webp",
        alt: "List",
        title: "List of items",
        desc: "Screen where a list of items available to the user is displayed depending on the chosen section, in this case, the students."
              },
        {
        src: "img/ot23/detail.webp",
        alt: "Detail",
        title: "Element detail",
        desc: "Detailed view of a specific element selected from the list, in this case the student Álex Marquez."
              },
        {
        src: "img/ot23/search_result.webp",
        alt: "Search result",
        title: "Search result",
        desc: "Screen with the results filtered according to the criteria entered by the user. The filter takes into account the first and last names in the case of judges, to which we add the cities and music styles for students, and the subjects taught in the case of teachers."
      }
    ],
  },

  polaris: {
    es: [
      {
        src: "img/polaris/mainpage.webp",
        alt: "Página principal",
        title: "Página principal",
        desc: "Pantalla de inicio del banco online Polaris, con publicidad propia de la entidad y acceso a la zona de usuario"
      },
      {
        src: "img/polaris/login.webp",
        alt: "Inicio de sesión",
        title: "Inicio de sesión",
        desc: "Pantalla de login para acceder al sistema bancario."
      },
      {
        src: "img/polaris/profile.webp",
        alt: "Perfil",
        title: "Perfil del usuario",
        desc: "Sección de perfil donde el usuario puede consultar sus cuentas, tarjetas y movimientos bancarios."
      },
      {
        src: "img/polaris/account_modification.webp",
        alt: "Modificación de cuenta",
        title: "Modificar cuenta",
        desc: "Pantalla para editar la información de una cuenta bancaria existente. También pueden modificarse las tarjetas asociadas a la cuenta."
      },
      {
        src: "img/polaris/new_account.webp",
        alt: "Nueva cuenta",
        title: "Crear nueva cuenta",
        desc: "Formulario para abrir una nueva cuenta bancaria. También se pueden crear nuevas tarjetas asociadas a la cuenta."
      },
      {
        src: "img/polaris/new_transaction.webp",
        alt: "Nueva transacción",
        title: "Nueva transacción",
        desc: "Pantalla para realizar una transacción de dinero entre cuentas."
      },
      {
        src: "img/polaris/transaction_detail.webp",
        alt: "Detalle de transacción",
        title: "Detalle de transacción",
        desc: "Vista detallada de una transacción específica y el pdf que se puede generar con la información del propio movimiento."
      },
      {
        src: "img/polaris/movements_csv.webp",
        alt: "Exportar movimientos",
        title: "Exportar movimientos (CSV)",
        desc: "Permite exportar los movimientos bancarios en formato CSV."
      },
      {
        src: "img/polaris/urls.webp",
        alt: "URLs del sistema",
        title: "Gestión de URLs",
        desc: "Pequeña muestra de la internacionalización de las urls de la web, que cambian en función del idioma escogido."
      }
    ],
    en: [
      {
        src: "img/polaris/mainpage.webp",
        alt: "Home page",
        title: "Home page",
        desc: "Home screen of the Polaris online bank, featuring the institution’s own ads and access to the user area."
      },
      {
        src: "img/polaris/login.webp",
        alt: "Login",
        title: "Login",
        desc: "Login screen to access the banking system."
      },
      {
        src: "img/polaris/profile.webp",
        alt: "Profile",
        title: "User profile",
        desc: "Profile section where the user can view their accounts, cards, and bank transactions."
      },
      {
        src: "img/polaris/account_modification.webp",
        alt: "Account modification",
        title: "Edit account",
        desc: "Screen for editing the information of an existing bank account. Associated cards can also be modified."
      },
      {
        src: "img/polaris/new_account.webp",
        alt: "New account",
        title: "Create new account",
        desc: "Form to open a new bank account. New cards linked to the account can also be created."
      },
      {
        src: "img/polaris/new_transaction.webp",
        alt: "New transaction",
        title: "New transaction",
        desc: "Screen to perform a money transfer between accounts."
      },
      {
        src: "img/polaris/transaction_detail.webp",
        alt: "Transaction detail",
        title: "Transaction detail",
        desc: "Detailed view of a specific transaction, including a downloadable PDF with the transaction information."
      },
      {
        src: "img/polaris/movements_csv.webp",
        alt: "Export transactions",
        title: "Export transactions (CSV)",
        desc: "Allows exporting bank transactions in CSV format."
      },
      {
        src: "img/polaris/urls.webp",
        alt: "System URLs",
        title: "URL management",
        desc: "A brief demonstration of the website’s URL internationalization, which changes depending on the selected language."
      }
    ]
  }
};

const currentLang = document.documentElement.lang === 'en' ? 'en' : 'es';
let currentProject = 'jhoola';
let currentSlide = 0;

function renderCarousel() {
  const data = carouselData[currentProject][currentLang];
  const img = document.getElementById('carousel-img');
  const title = document.getElementById('carousel-title');
  const desc = document.getElementById('carousel-desc');

  img.src = data[currentSlide].src;
  img.alt = data[currentSlide].alt;
  title.textContent = data[currentSlide].title;
  desc.textContent = data[currentSlide].desc;
}

function nextSlide() {
  const data = carouselData[currentProject][currentLang];
  currentSlide = (currentSlide + 1) % data.length;
  renderCarousel();
}

function prevSlide() {
  const data = carouselData[currentProject][currentLang];
  currentSlide = (currentSlide - 1 + data.length) % data.length;
  renderCarousel();
}

function changeProject(project) {
  currentProject = project;
  currentSlide = 0;
  renderCarousel();
}

document.addEventListener('DOMContentLoaded', function () {
  
  const prevBtn = document.getElementById('carousel-prev');
  const nextBtn = document.getElementById('carousel-next');
  prevBtn.addEventListener('click', prevSlide);
  nextBtn.addEventListener('click', nextSlide);

  
  document.getElementById('btn-jhoola').addEventListener('click', () => changeProject('jhoola'));
  document.getElementById('btn-ot23').addEventListener('click', () => changeProject('ot23'));
  document.getElementById('btn-polaris').addEventListener('click', () => changeProject('polaris'));

  renderCarousel();
});